### ISSUE TITLE
Morning Session Suggesstions

### ISSUE THREAD

**Issue by topeogunleye** [ShadyShawkat/Module1-Capstone#2]
## Morning Session Suggesstions
- We think you did a great Job

**Comment by RayhanTabase** [comment]
Great work so far everything looks great.
The only suggestion I have is that I think maybe giving the navbar a background that stands out from the main content could make the project look even more awesome.

**Comment by ShadyShawkat** [comment]
Hey @topeogunleye and @RayhanTabase, thank you for taking the time to check out my project. 🙏🏻 
I'll definitely consider your feedback.
